# Generated by Django 5.1.7 on 2025-03-19 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immediate_relief', '0002_media_remove_requestrescue_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestrescue',
            name='media',
        ),
        migrations.AddField(
            model_name='media',
            name='rescue_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='immediate_relief.requestrescue'),
            preserve_default=False,
        ),
    ]
