# Generated by Django 5.1.7 on 2025-03-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immediate_relief', '0003_remove_requestrescue_media_media_rescue_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestrescue',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
