# Generated by Django 5.1.7 on 2025-03-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immediate_relief', '0004_alter_requestrescue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, upload_to='rescue_images/'),
        ),
        migrations.AlterField(
            model_name='requestrescue',
            name='additional_information',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requestrescue',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='requestrescue',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='requestrescue',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requestrescue',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='requestrescue',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
