# Generated by Django 5.1.7 on 2025-03-23 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immediate_relief', '0005_alter_media_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='rescue_instance',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='immediate_relief.requestrescue'),
        ),
    ]
